$ Mission configuration for Apf11(21878) FwRev 031524:
$ AscentTimeOut(540) [min]
$ AtDialCmd(AT+CBST=71,0,1;DT00881600005496) [primary]
$ AltDialCmd(ATDT0012066163256) [alternate]
$ BuoyancyNudge(10) [count]
$ CompensatorHyperRetraction(0) [count]
$ ConnectTimeOut(60) [sec]
$ CpActivationP(985) [dbar]
$ DeepProfileDescentTime(240) [min]
$ DeepProfilePistonPos(16) [count]
$ DeepProfilePressure(2020) [dbar]
$ DownTime(14400) [min]
$ DuraRefWarmUpHrs(255)
$ DuraInit(-1) [Enable<0, Disable=0, Enable&Init>0]
$ FatFsEnable(1)
$ FlbbMode(1)
$ FloatId(21878)
$ FullExtension(231) [count]
$ FullRetraction(9) [count]
$ InitialBuoyancyNudge(22) [count]
$ IsusInit(-1) [Enable<0, Disable=0, Enable&Init>0]
$ MaxAirBladder(154) [count]
$ MaxLogKb(50) [KByte]
$ MissionPrelude(360) [min]
$ OcrInit(-500) [dbar]
$ OkVacuum(237) [count]
$ OptodeMode(1)
$ PActivationPistonPosition(16) [count]
$ ParkDescentTime(240) [min]
$ ParkPistonPos(66) [count]
$ ParkPressure(1000) [dbar]
$ PnPCycleLen(1)
$ TelemetryRetry(15) [min]
$ TimeOfDay(DISABLED) [min]
$ UpTime(660) [min]
$ ZModemTimeOut(80) [sec]
$ Verbosity(2)
$ DebugBits(0x0002)
$
# GPS fix obtained in 23 seconds.
#          lon      lat mm/dd/yyyy hhmmss nsat
Fix:  141.8021  15.0651 08/05/2025 034330    8
IridiumGeo: <x,y,z>: -4840km  3808km  1644km IrSysTime: 0xeace8dcb
IridiumFix: <lon,lat>:  141.805  15.042 IrEpoch: 1754364708sec 08/05/2025 03:31:48
Apf11FwRev=031524
ActiveBallastAdjustments=0
AirBladderPressure=156
AirPumpAmps=23
AirPumpVolts=218
BuoyancyPumpOnTime=1197
BuoyancyPumpAmps=0
BuoyancyPumpVolts=0
ConnectionAttempts=1
Connections=1
Coulombs=11.2kC
CoulombsDescent=0.0kC
CoulombsPark=0.0kC
CoulombsPrfDescent=0.0kC
CoulombsProfile=0.0kC
CoulombsSleep=0.7kC
CoulombsTelemetry=11.2kC
CoulombsWake=9.3kC
CurrentPistonPosition=231
DeepProfilePistonPosition=16
DuraPowerCycleCounter=0
DuraWakeCurrent=0.0mA
DuraWakePower=0.0mW
DuraWakeVolts=0.0V
FlbbAmps=0
FlbbStatus=0x00
FlbbVolts=0
FloatId=21878
GpsFixTime=23
HumidityAd12Park=0 (-23.8%)
HumidityAd12Pneumatic=0 (-23.8%)
HumidityAd12PneumaticRef=0 (-23.8%)
IsusPowerCycleCounter=0
IsusWakeCurrent=0.0mA
IsusWakePower=0.0mW
IsusWakeVolts=0.0V
MuxerTemperature=0.00C
MuxerHumidity=0.0%
MuxerWakeCurrent=0.0mA
MuxerWakePower=0.0mW
MuxerWakeVolts=0.0V
ObsIndex=0
OcrAmps=0
OcrStatuss=0x00
OcrVolts=0
OptodeAmps=0
OptodeVolts=0
ParkDescentPCnt=0
ParkPistonPosition=66
ParkObs={ 0.0dbar, 0.000C, 0.0000PSU / nan / 0.000C 0.000 0.000 / 0, 0, 0}
ProfileId=000
QuiescentAmps=0
QuiescentVolts=0
RtcSkew=-1
Sbe41cpAmps=0
Sbe41cpStatus=0x00000000
Sbe41cpVolts=0
SleepSec=14091
StandbySec=7723529
status=0x00000000
SurfaceObs={ -0.2dbar, nan, nan / nan / 29.783C 29.036 7.504 / 50, 118, 528}
SurfacePistonPosition=0
SurfacePressure=0.00
TimeStartDescent=0                  
TimeStartPark=0                     
TimeStartProfileDescent=0           
TimeStartProfile=0                  
TimeStopProfile=0                   
TimeStartTelemetry=1754365315       Aug 05 2025 03:41:55
Vacuum=210
WakeCycles=7271
WakeSec=7530

<EOT>
