$ SBD MSG Generator [SwiftWare]
$ $Revision$ $Date$
$ /net/sbd/23124/bin/Apf11SbdSbe41cp091723-msggen if=23124.000.msg.bin of=23124.000.msg
$
$ Mission configuration for Apf11(23124) FwRev 091723:
$ AscentTimeOut(540) [min]
$ BuoyancyNudge(10) [count]
$ CompensatorHyperRetraction(0) [count]
$ CpActivationP(985) [dbar]
$ DeepProfileDescentTime(240) [min]
$ DeepProfilePistonPos(16) [count]
$ DeepProfilePressure(2020) [dbar]
$ DownTime(14400) [min]
$ FatFsEnable(1)
$ FloatId(23124)
$ FullExtension(231) [count]
$ FullRetraction(9) [count]
$ InitialBuoyancyNudge(22) [count]
$ MaxAirBladder(154) [count]
$ MaxLogKb(40) [KByte]
$ MissionPrelude(360) [min]
$ OkVacuum(237) [count]
$ PActivationPistonPosition(16) [count]
$ ParkDescentTime(240) [min]
$ ParkPistonPos(66) [count]
$ ParkPressure(1000) [dbar]
$ PnPCycleLen(1)
$ SbeConfig(2,2,2;1000,1500) [dbar]
$ TelemetryRetry(15) [min]
$ TelemetryTimeOutMin(300) [sec]
$ TelemetryTimeOutPerMsg(60) [sec]
$ TimeOfDay(DISABLED) [min]
$ UpTime(660) [min]
$ Verbosity(2)
$ DebugBits(0x0002)
$ debugbits(0x0002)
$
ParkPt: Empty set of park-level PT samples.
$ Discrete samples: 0
# Empty Sbe41cp CP profile.
# GPS fix obtained in 24 seconds.
#         lon     lat mm/dd/yyyy hhmmss nsat
Fix:  153.302 -45.316 12/01/2025 215000    7
IridiumGeo: <x,y,z>: -4776km   432km -4188km IrSysTime: 0xf074a4b0
IridiumFix: <lon,lat>:  174.832 -41.321 IrEpoch: 1762894090sec 11/11/2025 20:48:10
Apf11FwRev=091723
ActiveBallastAdjustments=0
AirBladderPressure=157
AirPumpAmps=27
AirPumpVolts=213
BuoyancyPumpOnTime=1129
BuoyancyPumpAmps=0
BuoyancyPumpVolts=0
Coulombs=0.9kC
CoulombsDescent=0.0
CoulombsPark=0.0
CoulombsPrfDescent=0.0
CoulombsProfile=0.0
CoulombsSleep=0.0kC
CoulombsTelemetry=1.1
DeepProfilePistonPosition=16
FloatId=23124
GpsFixTime=24
HumidityAd12Park=0
HumidityAd12Pneumatic=0
HumidityAd12PneumaticRef=0
ObsIndex=0
ParkDescentPCnt=0
ParkPistonPosition=66
ParkPOutOfBand=0
ParkObs={ 0.0dbar, 0.000C, 0.0000PSU }
ProfileId=000
PtIndex=0
QuiescentAmps=0
QuiescentVolts=0
RtcSkew=0
Sbe41cpAmps=0
Sbe41cpVolts=0
Sbe41cpStatus=0x00000000
SleepSec=17305 sec
StandbySec=1723612
status=0x00000020
SurfacePistonPosition=0
SurfacePressure=0.00
TimeStartDescent=0                  
TimeStartPark=0                     
TimeStartProfileDescent=0           
TimeStartProfile=0                  
TimeStopProfile=0                   
TimeStartTelemetry=1764625688       Dec 01 2025 21:48:08
Vacuum=206
WakeCycles=296
WakeSec=4361 sec

<EOT>
