$ Mission configuration for Apf11(23808) FwRev 061125:
$ AscentTimeOut(540) [min]
$ AtDialCmd(AT+CBST=71,0,1;DT00881600005496) [primary]
$ AltDialCmd(ATDT0012066163256) [alternate]
$ BuoyancyNudge(10) [count]
$ CompensatorHyperRetraction(0) [count]
$ ConnectTimeOut(60) [sec]
$ CpActivationP(985) [dbar]
$ DeepProfileDescentTime(120) [min]
$ DeepProfilePistonPos(25) [count]
$ DeepProfilePressure(1200) [dbar]
$ DownTime(540) [min]
$ DuraRefWarmUpHrs(255)
$ DuraInit(-1) [Enable<0, Disable=0, Enable&Init>0]
$ FatFsEnable(1)
$ FlbbMode(1)
$ FloatId(23808)
$ FullExtension(231) [count]
$ FullRetraction(9) [count]
$ InitialBuoyancyNudge(22) [count]
$ IsusInit(-1) [Enable<0, Disable=0, Enable&Init>0]
$ MaxAirBladder(154) [count]
$ MaxLogKb(60) [KByte]
$ MissionPrelude(360) [min]
$ OcrInit(-500) [dbar]
$ OkVacuum(230) [count]
$ OptodeMode(1)
$ PActivationPistonPosition(16) [count]
$ ParkDescentTime(240) [min]
$ ParkPistonPos(70) [count]
$ ParkPressure(800) [dbar]
$ PnPCycleLen(1)
$ TelemetryRetry(15) [min]
$ TimeOfDay(DISABLED) [min]
$ UpTime(660) [min]
$ ZModemTimeOut(80) [sec]
$ Verbosity(2)
$ DebugBits(0x0002)
$
# GPS fix obtained in 31 seconds.
#          lon      lat mm/dd/yyyy hhmmss nsat
Fix: -157.9932  27.5223 09/25/2025 124040    5
IridiumGeo: <x,y,z>: -5244km -2120km  2928km IrSysTime: 0xedbf14ba
IridiumFix: <lon,lat>: -157.988  27.525 IrEpoch: 1758803293sec 09/25/2025 12:28:13
Apf11FwRev=061125
ActiveBallastAdjustments=0
AirBladderPressure=157
AirPumpAmps=22
AirPumpVolts=218
BuoyancyPumpOnTime=1079
BuoyancyPumpAmps=0
BuoyancyPumpVolts=0
ConnectionAttempts=1
Connections=1
Coulombs=2.0kC
CoulombsDescent=0.0kC
CoulombsPark=0.0kC
CoulombsPrfDescent=0.0kC
CoulombsProfile=0.0kC
CoulombsSleep=0.0kC
CoulombsTelemetry=2.0kC
CoulombsWake=2.0kC
CurrentPistonPosition=231
DeepProfilePistonPosition=25
DuraPowerCycleCounter=0
DuraWakeCurrent=0.0mA
DuraWakePower=0.0mW
DuraWakeVolts=0.0V
FlbbAmps=0
FlbbStatus=0x00
FlbbVolts=0
FloatId=23808
GpsFixTime=31
HumidityAd12Park=0 (-23.8%)
HumidityAd12Pneumatic=0 (-23.8%)
HumidityAd12PneumaticRef=0 (-23.8%)
IsusPowerCycleCounter=0
IsusWakeCurrent=0.0mA
IsusWakePower=0.0mW
IsusWakeVolts=0.0V
LeakDetectorChan[0]={sample:0xf state:0 count:0 epoch:1758783403 mtime:1094}
LeakDetectorChan[1]={sample:0xf state:0 count:0 epoch:1758783403 mtime:1094}
LeakDetectorChan[2]={sample:0xf state:0 count:0 epoch:1758783403 mtime:1094}
LeakDetectorChan[3]={sample:0xf state:0 count:0 epoch:1758783403 mtime:1094}
LeakSensor={state:0, count:0, ad12:3868cnt, v:2.36V, index:0.0%, epoch:1758783403sec, mtime:1094sec}
MuxerTemperature=0.00C
MuxerHumidity=0.0%
MuxerWakeCurrent=0.0mA
MuxerWakePower=0.0mW
MuxerWakeVolts=0.0V
ObsIndex=0
OcrAmps=0
OcrStatuss=0x00
OcrVolts=0
OptodeAmps=0
OptodeVolts=0
ParkDescentPCnt=0
ParkPistonPosition=70
ParkObs={ 0.0dbar, 0.000C, 0.0000PSU / nan / 0.000C 0.000 0.000 / 0, 0, 0}
ProfileId=000
QuiescentAmps=0
QuiescentVolts=0
RtcSkew=-4
Sbe41cpAmps=0
Sbe41cpStatus=0x00000000
Sbe41cpVolts=0
SleepSec=14034
StandbySec=397490
status=0x00000000
SurfaceObs={ 0.1dbar, nan, nan / nan / 26.511C 29.484 8.572 / 55, 136, 535}
SurfacePistonPosition=0
SurfacePressure=0.00
TimeStartDescent=0                  
TimeStartPark=0                     
TimeStartProfileDescent=0           
TimeStartProfile=0                  
TimeStopProfile=0                   
TimeStartTelemetry=1758803923       Sep 25 2025 12:38:43
Vacuum=209
WakeCycles=86
WakeSec=7588

<EOT>
