$ Mission configuration for Apf11(22205) FwRev 122122:
$ AscentTimeOut(540) [min]
$ AtDialCmd(AT+CBST=71,0,1;DT00881600005496) [primary]
$ AltDialCmd(ATDT0012066163256) [alternate]
$ BuoyancyNudge(10) [count]
$ CompensatorHyperRetraction(0) [count]
$ ConnectTimeOut(60) [sec]
$ CpActivationP(2005) [dbar]
$ DeepProfileDescentTime(240) [min]
$ DeepProfilePistonPos(16) [count]
$ DeepProfilePressure(2020) [dbar]
$ DownTime(14400) [min]
$ FatFsEnable(1)
$ FloatId(22205)
$ FullExtension(231) [count]
$ FullRetraction(9) [count]
$ InitialBuoyancyNudge(22) [count]
$ MaxAirBladder(154) [count]
$ MaxLogKb(40) [KByte]
$ MissionPrelude(360) [min]
$ OkVacuum(237) [count]
$ PActivationPistonPosition(16) [count]
$ ParkDescentTime(240) [min]
$ ParkPistonPos(66) [count]
$ ParkPressure(1000) [dbar]
$ PnPCycleLen(1)
$ RbrHiResP(50)
$ RbrConfig(2,2,4;200,2000)
$ RbrSalProc(1)
$ TelemetryRetry(15) [min]
$ TimeOfDay(DISABLED) [min]
$ UpTime(660) [min]
$ ZModemTimeOut(80) [sec]
$ Verbosity(2)
$ DebugBits(0x0002)
$
# GPS fix obtained in 6 seconds.
#          lon      lat mm/dd/yyyy hhmmss nsat
Fix: -144.9818  40.1921 07/09/2024 045140    8
IridiumGeo: <x,y,z>: -3996km -2796km  4092km IrSysTime: 0xd4611706
IridiumFix: <lon,lat>: -145.020  40.187 IrEpoch: 1720500176sec 07/09/2024 04:42:56
Apf11FwRev=122122
ActiveBallastAdjustments=0
AirBladderPressure=155
AirPumpAmps=27
AirPumpVolts=215
BuoyancyPumpOnTime=1191
BuoyancyPumpAmps=0
BuoyancyPumpVolts=0
ConnectionAttempts=1
Connections=1
CurrentPistonPosition=231
Coulombs=1.8kC
CoulombsDescent=0.0kC
CoulombsPark=0.0kC
CoulombsPrfDescent=0.0kC
CoulombsProfile=0.0kC
CoulombsSleep=0.0kC
CoulombsTelemetry=2.1kC
DeepProfilePistonPosition=16
FloatId=22205
GpsFixTime=6
HumidityAd12Park=0 (-23.8%)
HumidityAd12Pneumatic=0 (-23.8%)
HumidityAd12PneumaticRef=0 (-23.8%)
ObsIndex=0
ParkDescentPCnt=0
ParkPistonPosition=66
ParkObs={ 0.0dbar, 0.000C, 0.0000PSU  0.0000S/m 0.000C}
ProfileId=000
QuiescentAmps=0
QuiescentVolts=0
RtcSkew=-4
RbrAmps=0
RbrJoules=0
RbrVolts=0
RbrStatus=0x00000000
SleepSec=15832
StandbySec=2887707
status=0x00000000
SurfacePistonPosition=0
SurfacePressure=0.00
TimeStartDescent=0                  
TimeStartPark=0                     
TimeStartProfileDescent=0           
TimeStartProfile=0                  
TimeStopProfile=0                   
TimeStartTelemetry=1720500625       Jul 09 2024 04:50:25
Vacuum=203
WakeCycles=483
WakeSec=5789

<EOT>
