$ Mission configuration for Apf11(23031) FwRev 121123:
$ AscentTimeOut(500) [min]
$ AtDialCmd(AT+CBST=71,0,1;DT00881600005496) [primary]
$ AltDialCmd(ATDT0012066163256) [alternate]
$ BuoyancyNudge(10) [count]
$ CompensatorHyperRetraction(0) [count]
$ ConnectTimeOut(60) [sec]
$ CpActivationP(985) [dbar]
$ DeepProfileDescentTime(240) [min]
$ DeepProfilePistonPos(16) [count]
$ DeepProfilePressure(2020) [dbar]
$ DownTime(14400) [min]
$ FatFsEnable(1)
$ FloatId(23031)
$ FullExtension(231) [count]
$ FullRetraction(9) [count]
$ InitialBuoyancyNudge(22) [count]
$ MaxAirBladder(154) [count]
$ MaxLogKb(50) [KByte]
$ MissionPrelude(360) [min]
$ OkVacuum(237) [count]
$ PActivationPistonPosition(16) [count]
$ ParkDescentTime(240) [min]
$ ParkPistonPos(66) [count]
$ ParkPressure(1000) [dbar]
$ PnPCycleLen(1)
$ TelemetryRetry(15) [min]
$ TimeOfDay(DISABLED) [min]
$ UpTime(660) [min]
$ ZModemTimeOut(80) [sec]
$ Verbosity(2)
$ DebugBits(0x0002)
$
# GPS fix obtained in 31 seconds.
#          lon      lat mm/dd/yyyy hhmmss nsat
Fix: -102.9669 -48.9776 11/27/2024 155220    4
IridiumGeo: <x,y,z>:  -940km -4084km -4788km IrSysTime: 0xdc793e0c
IridiumFix: <lon,lat>: -102.962 -48.995 IrEpoch: 1732722228sec 11/27/2024 15:43:48
Apf11FwRev=121123
ActiveBallastAdjustments=0
AirBladderPressure=155
AirPumpAmps=31
AirPumpVolts=212
BuoyancyPumpOnTime=1132
BuoyancyPumpAmps=0
BuoyancyPumpVolts=0
ConnectionAttempts=2
Connections=1
Coulombs=1.9kC
CoulombsDescent=0.0kC
CoulombsPark=0.0kC
CoulombsPrfDescent=0.0kC
CoulombsProfile=0.0kC
CoulombsSleep=0.0kC
CoulombsTelemetry=1.9kC
CoulombsWake=1.6kC
CurrentPistonPosition=231
DeepProfilePistonPosition=16
FloatId=23031
GpsFixTime=31
HumidityAd12Park=0 (-23.8%)
HumidityAd12Pneumatic=0 (-23.8%)
HumidityAd12PneumaticRef=0 (-23.8%)
ObsIndex=0
ParkDescentPCnt=0
ParkPistonPosition=66
ParkObs={ 0.0dbar, 0.000C, 0.0000PSU }
ProfileId=000
QuiescentAmps=0
QuiescentVolts=0
RtcSkew=1
Sbe41cpAmps=0
Sbe41cpStatus=0x00000000
Sbe41cpVolts=0
SleepSec=13919
StandbySec=2891529
status=0x00000000
SurfacePistonPosition=0
SurfacePressure=0.00
TimeStartDescent=0                  
TimeStartPark=0                     
TimeStartProfileDescent=0           
TimeStartProfile=0                  
TimeStopProfile=0                   
TimeStartTelemetry=1732722615       Nov 27 2024 15:50:15
Vacuum=198
WakeCycles=478
WakeSec=7695

<EOT>
