$ Mission configuration for Apf11(24583) FwRev 070325:
$ AirCalSamplePeriod(20) [sec]
$ AscentTimeOut(540) [min]
$ AtDialCmd(AT+CBST=71,0,1;DT00881600005496) [primary]
$ AltDialCmd(ATDT0012066163256) [alternate]
$ BuoyancyNudge(10) [count]
$ CompensatorHyperRetraction(0) [count]
$ ConnectTimeOut(60) [sec]
$ CpActivationP(985) [dbar]
$ DeepProfileDescentTime(240) [min]
$ DeepProfilePistonPos(16) [count]
$ DeepProfilePressure(2020) [dbar]
$ DownTime(14400) [min]
$ DuraRefWarmUpHrs(255)
$ DuraInit(-1) [Enable<0, Disable=0, Enable&Init>0]
$ FatFsEnable(1)
$ FlbbMode(1)
$ FloatId(24583)
$ FullExtension(231) [count]
$ FullRetraction(9) [count]
$ InitialBuoyancyNudge(22) [count]
$ IsusInit(-1) [Enable<0, Disable=0, Enable&Init>0]
$ MaxAirBladder(154) [count]
$ MaxLogKb(60) [KByte]
$ MissionPrelude(360) [min]
$ OkVacuum(237) [count]
$ PActivationPistonPosition(16) [count]
$ ParkDescentTime(240) [min]
$ ParkPistonPos(66) [count]
$ ParkPressure(1000) [dbar]
$ PnPCycleLen(1)
$ Sbe83Init(-1)
$ TelemetryRetry(15) [min]
$ TimeOfDay(DISABLED) [min]
$ UpTime(660) [min]
$ ZModemTimeOut(80) [sec]
$ Verbosity(2)
$ DebugBits(0x0002)
$
# GPS fix obtained in 9 seconds.
#          lon      lat mm/dd/yyyy hhmmss nsat
Fix: -130.2367  31.5384 04/03/2026 032800    7
IridiumGeo: <x,y,z>: -3512km -4152km  3316km IrSysTime: 0x1798beca
IridiumFix: <lon,lat>: -130.226  31.544 IrEpoch: 1435448000sec 06/27/2015 23:33:20
Apf11FwRev=070325
ActiveBallastAdjustments=0
AirBladderPressure=156
AirPumpAmps=30
AirPumpVolts=212
BuoyancyPumpOnTime=1115
BuoyancyPumpAmps=0
BuoyancyPumpVolts=0
ConnectionAttempts=1
Connections=1
Coulombs=2.0kC
CoulombsDescent=0.0kC
CoulombsPark=0.0kC
CoulombsPrfDescent=0.0kC
CoulombsProfile=0.0kC
CoulombsSleep=0.0kC
CoulombsTelemetry=2.0kC
CoulombsWake=1.9kC
CurrentPistonPosition=231
DeepProfilePistonPosition=16
DuraPowerCycleCounter=0
DuraWakeCurrent=0.0mA
DuraWakePower=0.0mW
DuraWakeVolts=0.0V
FlbbAmps=0
FlbbStatus=0x00
FlbbVolts=0
FloatId=24583
GpsFixTime=9
HumidityAd12Park=0 (-23.8%)
HumidityAd12Pneumatic=0 (-23.8%)
HumidityAd12PneumaticRef=0 (-23.8%)
IsusPowerCycleCounter=0
IsusWakeCurrent=0.0mA
IsusWakePower=0.0mW
IsusWakeVolts=0.0V
LeakDetectorChan[0]={sample:0xe state:1 count:0 epoch:1775166179 mtime:1130}
LeakDetectorChan[1]={sample:0xe state:0 count:0 epoch:1775166179 mtime:1130}
LeakDetectorChan[2]={sample:0xe state:0 count:0 epoch:1775166179 mtime:1130}
LeakDetectorChan[3]={sample:0xe state:0 count:0 epoch:1775166179 mtime:1130}
LeakSensor={state:0, count:0, ad12:3851cnt, v:2.35V, index:0.0%, epoch:1775166179sec, mtime:1130sec}
MuxerTemperature=0.00C
MuxerHumidity=0.0%
MuxerWakeCurrent=0.0mA
MuxerWakePower=0.0mW
MuxerWakeVolts=0.0V
ObsIndex=0
ParkDescentPCnt=0
ParkPistonPosition=66
ParkObs={ 0.0dbar, 0.000C, 0.0000PSU / nan / 0.000C 0.000 / {0, 0}, 0, 0}
ProfileId=000
QuiescentAmps=0
QuiescentVolts=0
RtcSkew=-16
Sbe41cpAmps=0
Sbe41cpStatus=0x00000000
Sbe41cpVolts=0
Sbe83Amps=0
Sbe83Volts=0
SleepSec=14558
StandbySec=888954
status=0x00000000
SurfaceObs={ 0.2dbar, nan, nan / nan / 16.899C 17.833 / {50, 48}, 101, 546}
SurfacePistonPosition=0
SurfacePressure=0.00
TimeStartDescent=0                  
TimeStartPark=0                     
TimeStartProfileDescent=0           
TimeStartProfile=0                  
TimeStopProfile=0                   
TimeStartTelemetry=1775186768       Apr 03 2026 03:26:08
Vacuum=206
WakeCycles=165
WakeSec=7170

<EOT>
