$ Mission configuration for Apf11(23394) FwRev 102725:
$ AscentTimeOut(540) [min]
$ AtDialCmd(AT+CBST=71,0,1;DT00881600005496) [primary]
$ AltDialCmd(ATDT0012066163256) [alternate]
$ BuoyancyNudge(10) [count]
$ CompensatorHyperRetraction(0) [count]
$ ConnectTimeOut(60) [sec]
$ CpActivationP(985) [dbar]
$ DeepProfileDescentTime(240) [min]
$ DeepProfilePistonPos(16) [count]
$ DeepProfilePressure(2020) [dbar]
$ DownTime(14400) [min]
$ DuraRefWarmUpHrs(255)
$ DuraInit(-1) [Enable<0, Disable=0, Enable&Init>0]
$ FatFsEnable(1)
$ FlbbMode(1)
$ FloatId(23394)
$ FullExtension(231) [count]
$ FullRetraction(9) [count]
$ InitialBuoyancyNudge(22) [count]
$ IsusInit(-1) [Enable<0, Disable=0, Enable&Init>0]
$ MaxAirBladder(154) [count]
$ MaxLogKb(60) [KByte]
$ MissionPrelude(360) [min]
$ OkVacuum(237) [count]
$ OptodeMode(1)
$ PActivationPistonPosition(16) [count]
$ ParkDescentTime(240) [min]
$ ParkPistonPos(66) [count]
$ ParkPressure(1000) [dbar]
$ PnPCycleLen(1)
$ TelemetryRetry(15) [min]
$ TimeOfDay(DISABLED) [min]
$ UpTime(660) [min]
$ ZModemTimeOut(80) [sec]
$ Verbosity(2)
$ DebugBits(0x0002)
$
# GPS fix obtained in 10 seconds.
#          lon      lat mm/dd/yyyy hhmmss nsat
Fix: -140.0845  32.8894 04/05/2026 064220    6
IridiumGeo: <x,y,z>: -4112km -3440km  3440km IrSysTime: 0x17b7f6fb
IridiumFix: <lon,lat>: -140.085  32.861 IrEpoch: 1435632140sec 06/30/2015 02:42:20
Apf11FwRev=102725
ActiveBallastAdjustments=0
AirBladderPressure=157
AirPumpAmps=26
AirPumpVolts=215
BuoyancyPumpOnTime=1105
BuoyancyPumpAmps=0
BuoyancyPumpVolts=0
ConnectionAttempts=2
Connections=2
Coulombs=1.8kC
CoulombsDescent=0.0kC
CoulombsPark=0.0kC
CoulombsPrfDescent=0.0kC
CoulombsProfile=0.0kC
CoulombsSleep=0.0kC
CoulombsTelemetry=1.8kC
CoulombsWake=1.7kC
CurrentPistonPosition=231
DeepProfilePistonPosition=16
DuraPowerCycleCounter=0
DuraWakeCurrent=0.0mA
DuraWakePower=0.0mW
DuraWakeVolts=0.0V
FlbbAmps=0
FlbbStatus=0x00
FlbbVolts=0
FloatId=23394
GpsFixTime=10
HumidityAd12Park=0 (-23.8%)
HumidityAd12Pneumatic=0 (-23.8%)
HumidityAd12PneumaticRef=0 (-23.8%)
IsusPowerCycleCounter=0
IsusWakeCurrent=0.0mA
IsusWakePower=0.0mW
IsusWakeVolts=0.0V
LeakDetectorChan[0]={sample:0xe state:1 count:0 epoch:1775350764 mtime:1119}
LeakDetectorChan[1]={sample:0xe state:0 count:0 epoch:1775350764 mtime:1119}
LeakDetectorChan[2]={sample:0xe state:0 count:0 epoch:1775350764 mtime:1119}
LeakDetectorChan[3]={sample:0xe state:0 count:0 epoch:1775350764 mtime:1119}
LeakSensor={state:0, count:0, ad12:3837cnt, v:2.34V, index:0.0%, epoch:1775350764sec, mtime:1119sec}
MuxerTemperature=0.00C
MuxerHumidity=0.0%
MuxerWakeCurrent=0.0mA
MuxerWakePower=0.0mW
MuxerWakeVolts=0.0V
ObsIndex=0
OptodeAmps=0
OptodeVolts=0
ParkDescentPCnt=0
ParkPistonPosition=66
ParkObs={ 0.0dbar, 0.000C, 0.0000PSU / nan / 0.000C 0.000 0.000 / {0, 0}, 0, 0}
ProfileId=000
QuiescentAmps=0
QuiescentVolts=0
RtcSkew=-2
Sbe41cpAmps=0
Sbe41cpStatus=0x00000000
Sbe41cpVolts=0
SleepSec=14895
StandbySec=971138
status=0x00000000
SurfaceObs={ 0.2dbar, nan, nan / nan / 17.694C 31.579 7.895 / {50, 49}, 115, 546}
SurfacePistonPosition=0
SurfacePressure=0.00
TimeStartDescent=0                  
TimeStartPark=0                     
TimeStartProfileDescent=0           
TimeStartProfile=0                  
TimeStopProfile=0                   
TimeStartTelemetry=1775371258       Apr 05 2026 06:40:58
Vacuum=211
WakeCycles=173
WakeSec=6731

<EOT>
