$ Mission configuration for Apf11(23050) FwRev 022725:
$ AscentTimeOut(500) [min]
$ AtDialCmd(AT+CBST=71,0,1;DT00881600005496) [primary]
$ AltDialCmd(ATDT0012066163256) [alternate]
$ BuoyancyNudge(10) [count]
$ CompensatorHyperRetraction(0) [count]
$ ConnectTimeOut(60) [sec]
$ CpActivationP(985) [dbar]
$ DeepProfileDescentTime(240) [min]
$ DeepProfilePistonPos(12) [count]
$ DeepProfilePressure(2020) [dbar]
$ DownTime(14400) [min]
$ FatFsEnable(1)
$ FloatId(23050)
$ FullExtension(231) [count]
$ FullRetraction(9) [count]
$ InitialBuoyancyNudge(22) [count]
$ MaxAirBladder(154) [count]
$ MaxLogKb(50) [KByte]
$ MissionPrelude(360) [min]
$ OkVacuum(237) [count]
$ PActivationPistonPosition(16) [count]
$ ParkDescentTime(240) [min]
$ ParkPistonPos(60) [count]
$ ParkPressure(1000) [dbar]
$ PnPCycleLen(1)
$ TelemetryRetry(15) [min]
$ TimeOfDay(DISABLED) [min]
$ UpTime(660) [min]
$ ZModemTimeOut(80) [sec]
$ Verbosity(2)
$ DebugBits(0x0002)
$
# GPS fix obtained in 24 seconds.
#          lon      lat mm/dd/yyyy hhmmss nsat
Fix:  102.2677 -50.0017 02/07/2026 124930    4
IridiumGeo: <x,y,z>:  -872km  4012km -4860km IrSysTime: 0x1478ad57
IridiumFix: <lon,lat>:  102.262 -49.998 IrEpoch: 1430729006sec 05/04/2015 08:43:26
Apf11FwRev=022725
ActiveBallastAdjustments=0
AirBladderPressure=155
AirPumpAmps=36
AirPumpVolts=213
BuoyancyPumpOnTime=1144
BuoyancyPumpAmps=0
BuoyancyPumpVolts=0
ConnectionAttempts=2
Connections=2
Coulombs=2.8kC
CoulombsDescent=0.0kC
CoulombsPark=0.0kC
CoulombsPrfDescent=0.0kC
CoulombsProfile=0.0kC
CoulombsSleep=0.0kC
CoulombsTelemetry=2.8kC
CoulombsWake=1.9kC
CurrentPistonPosition=231
DeepProfilePistonPosition=12
FloatId=23050
GpsFixTime=24
HumidityAd12Park=0 (-23.8%)
HumidityAd12Pneumatic=0 (-23.8%)
HumidityAd12PneumaticRef=0 (-23.8%)
LeakSensor={state:0, count:0, ad12:3830cnt, v:2.34V, index:0.0%, epoch:1770448013sec, mtime:1157sec}
ObsIndex=0
ParkDescentPCnt=0
ParkPistonPosition=60
ParkObs={ 0.0dbar, 0.000C, 0.0000PSU }
ProfileId=000
QuiescentAmps=0
QuiescentVolts=0
RtcSkew=4
Sbe41cpAmps=0
Sbe41cpStatus=0x00000000
Sbe41cpVolts=0
SleepSec=13489
StandbySec=7459394
status=0x00000000
SurfacePistonPosition=0
SurfacePressure=0.00
TimeStartDescent=0                  
TimeStartPark=0                     
TimeStartProfileDescent=0           
TimeStartProfile=0                  
TimeStopProfile=0                   
TimeStartTelemetry=1770468469       Feb 07 2026 12:47:49
Vacuum=200
WakeCycles=1206
WakeSec=8133

<EOT>
